// Copyright 2024 Espressif Systems (Shanghai) PTE LTD
/* SPDX-License-Identifier: GPL-2.0-only OR Apache-2.0 */

#ifndef __ESP_FW_VERSION__H
#define __ESP_FW_VERSION__H

#define PROJECT_NAME                "NG"
#define PROJECT_VERSION_MAJOR_1     1
#define PROJECT_VERSION_MAJOR_2     0
#define PROJECT_VERSION_MINOR       5
#define PROJECT_REVISION_PATCH_1    0
#define PROJECT_REVISION_PATCH_2    5

#define STRINGIFY_HELPER(x)	#x
#define STRINGIFY(x)		STRINGIFY_HELPER(x)

#define RELEASE_VERSION	PROJECT_NAME "-" STRINGIFY(PROJECT_VERSION_MAJOR_1) "." STRINGIFY(PROJECT_VERSION_MAJOR_2) "." STRINGIFY(PROJECT_VERSION_MINOR) "." STRINGIFY(PROJECT_REVISION_PATCH_1) "." STRINGIFY(PROJECT_REVISION_PATCH_2)

#endif
